// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service.go
//
// Generated by this command:
//
//	mockgen -source=./internal/service.go -destination=./internal/mock_service.go -package=internal
//

// Package internal is a generated GoMock package.
package internal

import (
	model "location-api/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLocationDbStore is a mock of LocationDBStore interface.
type MockLocationDbStore struct {
	ctrl     *gomock.Controller
	recorder *MockLocationDbStoreMockRecorder
}

// MockLocationDbStoreMockRecorder is the mock recorder for MockLocationDbStore.
type MockLocationDbStoreMockRecorder struct {
	mock *MockLocationDbStore
}

// NewMockLocationDbStore creates a new mock instance.
func NewMockLocationDbStore(ctrl *gomock.Controller) *MockLocationDbStore {
	mock := &MockLocationDbStore{ctrl: ctrl}
	mock.recorder = &MockLocationDbStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocationDbStore) EXPECT() *MockLocationDbStoreMockRecorder {
	return m.recorder
}

// CreateLocation mocks base method.
func (m *MockLocationDbStore) CreateLocation(req *model.CreateLocationRequest) (*model.CreateLocationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLocation", req)
	ret0, _ := ret[0].(*model.CreateLocationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLocation indicates an expected call of CreateLocation.
func (mr *MockLocationDbStoreMockRecorder) CreateLocation(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLocation", reflect.TypeOf((*MockLocationDbStore)(nil).CreateLocation), req)
}
