// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/handler.go
//
// Generated by this command:
//
//	mockgen -source=./internal/handler.go -destination=./internal/mock_handler.go -package=internal
//

// Package internal is a generated GoMock package.
package internal

import (
	gomock "go.uber.org/mock/gomock"
)

// Mockactions is a mock of actions interface.
type Mockactions struct {
	ctrl     *gomock.Controller
	recorder *MockactionsMockRecorder
}

// MockactionsMockRecorder is the mock recorder for Mockactions.
type MockactionsMockRecorder struct {
	mock *Mockactions
}

// NewMockactions creates a new mock instance.
func NewMockactions(ctrl *gomock.Controller) *Mockactions {
	mock := &Mockactions{ctrl: ctrl}
	mock.recorder = &MockactionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockactions) EXPECT() *MockactionsMockRecorder {
	return m.recorder
}
