// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service.go
//
// Generated by this command:
//
//	mockgen -source=./internal/service.go -destination=./internal/mock_service.go -package=internal
//

// Package internal is a generated GoMock package.
package internal

import (
	gomock "go.uber.org/mock/gomock"
)

// MockLocationDbStore is a mock of LocationDbStore interface.
type MockLocationDbStore struct {
	ctrl     *gomock.Controller
	recorder *MockLocationDbStoreMockRecorder
}

// MockLocationDbStoreMockRecorder is the mock recorder for MockLocationDbStore.
type MockLocationDbStoreMockRecorder struct {
	mock *MockLocationDbStore
}

// NewMockLocationDbStore creates a new mock instance.
func NewMockLocationDbStore(ctrl *gomock.Controller) *MockLocationDbStore {
	mock := &MockLocationDbStore{ctrl: ctrl}
	mock.recorder = &MockLocationDbStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocationDbStore) EXPECT() *MockLocationDbStoreMockRecorder {
	return m.recorder
}
